spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8033 
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client
eureka: 
  instance:
    hostname: eurekaserver
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
---
server: 
  port: 8033 
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka:
  instance:
    hostname: eurekaserver
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/