spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: dev-config-client1
eureka: 
  client: 
    service-url:
      defaultZone: http://eurekaserver:8033/eureka/
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: test-config-client1
eureka: 
  client: 
    service-url:
      defaultZone: http://eurekaserver:8033/eureka/
